### ISSUE TITLE
admin area isnt working with login

### ISSUE THREAD

**Issue by jmb4444** [Phype/telnet-iot-honeypot#15]
in the config.yaml it gives me the login but it doesnt work in admin area how do i fix

**Comment by giantbranch** [comment]
i have the same problem @Phype

**Comment by jlgallegol** [comment]
i have the same problem, but i don´t know how to resolve it. Any solution?

**Comment by Phype** [comment]
The username/password in the config is only read at first start to create the admin user in the database. Changing the file afterwards will not have any effects, the username/password is than stored in the db (using an argon2 hash). If your database contains no important data, i would suggest to just scrap it and create a new one.

**Comment by windmzx** [comment]
I try to delete the database file and run "python backend.py" and I find the script created a new database file. I open the database file via SQLiteStudio. The data in "users" table is is newly created by myself. But I still can't log in .

I get the real reason. It is beacuse that  the "/login" url return "404 not found " rather than verify password failed.
