### ISSUE TITLE
Listen on multiple ports

### ISSUE THREAD

**Issue by timhux123** [Phype/telnet-iot-honeypot#22]
Is it possible to have the honeypot listen on multiple ports? I want the honeypot to listen on ports 23 and 2323. I have tried various configurations in config.dist.yaml at the following location but none work.

# Telnet port
telnet_addr: ""
telnet_port: 2323

**Comment by Phype** [comment]
No, the honeypot only supports a single port (or socket, actually). But you can start the honeypot multiple times from the same directory using the `-c` flag to provide another configuration file than the standard `config.yaml`. It makes sense in this case to add different users for each honeypot, so that the backend can differentiate between the different ports and does not falsely flag connections as being associated with each other when they appear on different ports. If you don't mind about that you could also use iptables to configure a port-forwarding from port 23->2323 or something like that.

**Comment by timhux123** [comment]
Thanks. Using the -c flag with a second config.yaml containing port 2323 did the trick.
Example of second config.yaml:
***************************************
backend_user: admin
backend_pass: ecadXXXXXXXXXXXXXXXXXXXXXX
backend_salt: 312f9XXXXXXXXXXXXXXXXXXXXXX

# Telnet port
telnet_addr: ""
telnet_port: 2323
***************************************
