### ISSUE TITLE
add hpfeeds support

### ISSUE THREAD

**Issue by dpicollege** [Phype/telnet-iot-honeypot#6]
Hello,
Could you add hpfeeds support for this honeypot?

**Comment by Phype** [comment]
Maybe someday, for now i am not working on the project myself.

**Comment by dpicollege** [comment]
ok after a long time could you add hpfeeds support?

**Comment by dpicollege** [comment]
thanks any intention to add hpfeeds to this project?

**Comment by Phype** [comment]
Is there any documentation on how to run an hpfeeds server and is anyone using that? Since the honeypot included in this project isn't great, i added an output module to cowrie to feed the backend ( https://github.com/Phype/cowrie ), which seemed way more simple than digging into how hpfeeds is supposed to work. To be clear: i'm not running this project on my own, so maybe if you can give me access to an running hpfeeds server/broker, then i might check out if i can build subscriber-functionality into the backend.
