### ISSUE TITLE
Not able to populate connections on database

### ISSUE THREAD

**Issue by f1r3walled** [Phype/telnet-iot-honeypot#9]
I see a lot of new connections coming though CLI, but no information is recorded in the webpage. I think that my db is facing any problem to populate this information.

This is my config.json:
root@vps:/opt/telnet-iot-honeypot# cat config.json
{
        "use_local_db": true,

        "user": "testuser",
        "backend": "http://MY_PUBLIC_IP:5000",

        "sql": "mysql+mysqldb://telhoney:xTAqFLqJ2AxAGDgV@localhost/telhoney",
        "max_db_conn": 1,
        "sql": "sqlite:///IoT.sqlite",
        "sample_dir": "samples",

        "save_samples": true,
        "vt_key": "MY_API",
        "submit_to_vt": false,

    "cuckoo_enabled": false,
    "cuckoo_url_base": "http://127.0.0.1:8090",
    "cuckoo_user": "user",
    "cuckoo_passwd": "passwd",
    "cuckoo_force": 0
}

How can I make it work according expected and see information on the main dashboard?

**Comment by Phype** [comment]
You've used `use_local_db: true` which means the honeypot will put the info in the db itself.
However, this way no backend is running, so the frontend cannot actually access the data in the database. You have to set `use_local_db: false` and restart the honeypot and the backend. 
If you want to check if anything is in the db, run `mysql` and do:

```
USE telhoney;
SELECT * from conns;
```

This should show contents of the connection table.
I updated the installation guide.

**Comment by f1r3walled** [comment]
I applied this change. I'm still not able to see connections and URL's in the front end.
Trust me, I'm trying to change a lot of things to make it work.
![workspace 1_002](https://user-images.githubusercontent.com/13592660/33810583-568a88dc-ddbb-11e7-8b53-f33222fd79c9.jpg)
It is everything that I can see, but behind this, taking a look through the CLI while logged in my server, it is working cause I can see a lot of connections being established.

Applying the mysql command that you mentioned, I have:
mysql> select * from conns;
ERROR 1146 (42S02): Table 'telhoney.conns' doesn't exist
mysql> show tables;
Empty set (0.00 sec)

Do I need to manually create those tables?

Thank you, man!

**Comment by Phype** [comment]
Ok, strange. To be clear, what config are you trying to use?
In your first post you have 2 "sql" entries one using a sqlite db and one a mysql one.

To clear things up:
The html page "frontend" uses javascript to talk to the backend server you start with `python backend.py`. This server provides a REST-api to fetch information from the db, and when `"use_local_db"` is deactivated, the honeypot (`python honeypot.py`) uses the same api to store connections.

You also have `"backend": "http://MY_PUBLIC_IP:5000"` in your config. This would mean the honeypot will use `MY_PUBLIC_IP` to connect to the backend. Since the honeypot and backend are probably running on the same machine, `localhost` should do it.
Also if you change the `"backend"` option, you may also need to change `html/apiurl.js`,
since this file contains the "configuration" for the javascript frontend. Here you may need to enter your ip, if you use the javascript frontend from another computer.

With the supplied info, i cannot tell you where your problem is. Maybe just backup your config and retry with this one:

    {
        "use_local_db": false,

        "user": "testuser",
        "backend": "http://localhost:5000",

        "sql": "sqlite:///database.db",
        "max_db_conn": 1,
        "sample_dir": "samples",

        "save_samples": false,
        "vt_key": "GET_YOUR_OWN",
        "submit_to_vt": false,

        "cuckoo_enabled": false,
        "cuckoo_url_base": "http://127.0.0.1:8090",
        "cuckoo_user": "user",
        "cuckoo_passwd": "passwd",
        "cuckoo_force": 0
    }

Now start `python backend.py` AND `python honeypot.py` and retry a telnet connection. The honeypot shoud now connect to the backend showing entries like
`127.0.0.1 - - [12/Dec/2017 14:56:16] "GET /connections HTTP/1.1" 200 -`
in the backend console. Watch for "PUT", this should be the client storing new connections.

best regards

edit: clarified some things

**Comment by f1r3walled** [comment]
So, I just made some adjustment according your last answer. I'm indicating only one DB in the config.json.
I see connections to the backend like "GET /connections ...", but I still see no result in the frontend.
What I see as most weird is that when I log into the mysql, I see no tables named "conns", The database is there, but there is no tables.

mysql> select * from conns;
ERROR 1146 (42S02): Table 'telhoney.conns' doesn't exist
mysql> show tables;
Empty set (0.00 sec)

I imagine that the problem is related to this point, don't you?
What OS are you using? I tried the deploy with Ubuntu 14 64, Ubuntu 16 64 and Debian 8 64. The result is ever the same.

**Comment by Phype** [comment]
I've used Ubuntu 16.04, 17.10 and Rasbian jessie.
The tables not even existing in mysql is very strange, the backend should definitely create them directly at startup. Isn't there any error message in the backend console? I cannot really imagining the thing just failing to create the db schema and failing without creating any exception message. Also, any request definitely should just fail, because it cannot read from the non-existing tables obviously.

Maybe i forgot something in the dependencies, I already have installed manually, like an python mysql db connector or something. Have you tried using sqlite? Maybe set sql to `sqlite:///test.db` and check if the file `test.db` is even created and if, if there are any tables. You can check the contents of sqlite files with the command `sqlite3`, it works like the `mysql` console client. A full dump of the backend console output may also help.

I'll try to check a fresh installation on a clean Ubuntu VM.

**Comment by f1r3walled** [comment]
Hello,
Before, I'd like to point some things that maybe can help the project development... OR NOT, hehe!

While following the INSTALL.md instructions:
1) It is intended that "pip install -r requirements.txt" should be executed before "git clone... ", and for sure it is not right, considering that "requirements.txt" will be inside the cloned .git;

2) Per our discussion, I build a new Ubuntu 14.04.1 64 bits cloud server. I just updated it with "apt-get update" and "apt-get upgrade" before install the project requirements, which is "apt-get install python-pip libmysqlclient-dev python-mysqldb git" and "pip install -r requirements.txt", but I got the following red error in the end of pip execution: 
![terminal - root ubuntu -opt-telnet-iot-honeypot_005](https://user-images.githubusercontent.com/13592660/34342466-d04ff304-e965-11e7-9c80-925daeac7cc9.png)

I solved it including "python-dev" in the requirements, so maybe you can check if it is required, too. I had no errors executing "pip install -r requirements.txt" after "python-dev" installation;

3) When running "python backend.py" by the first time, I got the following error:
root@ubuntu:/opt/telnet-iot-honeypot# python backend.py 
Traceback (most recent call last):
  File "backend.py", line 1, in <module>
    from backend.backend import app
  File "/opt/telnet-iot-honeypot/backend/backend.py", line 1, in <module>
    from flask import Flask, request, Response
  File "/usr/local/lib/python2.7/dist-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: No module named werkzeug.exceptions

Which I solved with "pip install werkzeug".
I had other errors like this, which was solved using: "pip install jinja2"; "pip install itsdangerous" and "pip install click", respectively.

Regarding the tshoot to make my installation work:
I tried to set sqlite:///test.db, which is the default database option and I see the file being created. It was not working before because my default VPS installation was missing an important dependendy, which is "sqlite3". Navigating through the database, I could see the proper tables but data isn't being recorded on those tables. The situation is the same for mysql, where I now I can see tables but no data being recorded.
To make the tables apper in mysql I just installed dependencies like "python-sql"; "pip install mysql-python" and a lot of other guesses regarding python/sql.

I'll keep my installation using mysql:
root@ubuntu:/opt/telnet-iot-honeypot# cat config.dist.yaml 
# sqlalchemy sql connect string
# examples:
# using sqlite: "sqlite:///database.db"
# using mysql:  ""mysql+mysqldb://USER:PASSWORD@MYSQL_HOST/DATABASE_NAME","
sql: "mysql+mysqldb://telhoney:MY_DATABASE_PASSWORD@localhost/telhoney"

root@ubuntu:/opt/telnet-iot-honeypot# mysql -u telhoney -p 
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| telhoney           |
+--------------------+
2 rows in set (0.00 sec)

mysql> use telhoney;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+--------------------+
| Tables_in_telhoney |
+--------------------+
| asn                |
| conns              |
| conns_assocs       |
| conns_tags         |
| conns_urls         |
| samples            |
| tags               |
| urls               |
| users              |
+--------------------+
9 rows in set (0.00 sec)

mysql> SELECT * from conns;
Empty set (0.00 sec)

Again, I'm seeing a lot of interaction, such as:
2017-12-25 16:39:58   telnet.py:72      Client connected at ('XX.XX.XX.XX', 58315)
2017-12-25 16:39:58   session.py:19     New Session
2017-12-25 16:39:58   telnet.py:98      Setting timeout to 15.0 seconds
2017-12-25 16:40:02   session.py:32     Session login: user=admin password=admin
2017-12-25 16:40:05   session.py:42     Downloaded http://XX.XX.XX.XX80/script.arm7 to script.arm7
2017-12-25 16:40:07   telnet.py:132     Connection closed
2017-12-25 16:40:07   session.py:49     Session End

But data isn't being shown in the tables and not even in the backend screen.

Thank you!

**Comment by Phype** [comment]
Hmm, sorry to say that, but i cannot really say where your problem is. Probably some issue with the SQLAlchemy library. Ubuntu 14.04 is quite old and i actually failed to install everything with pip there succesfully in a test VM myself.

I've included a Vagrantfile in the vagrant folder using a Ubuntu 16.04 cloudimage, which i have confirmed to work. If you could also use Ubuntu 16.04 on your VPS, i would highly recommend to use that, because it would be the same setup i can confirm to be working. You can just test it locally, install Vagrant (including the vagrant virtualbox provider) and run `vagrant up` in the vagrant/ folder. If it works copy the commands from the Vagrantfile to setup everything in the VPS. For mysql support, i try to create another Vagrantfile including a mysql server, but for now i'm out of time. Running vagrant INSIDE the VPS is probably a bad idea, because that would mean using nested-virtualisation which will probably not work or would by horribly slow.

**Comment by f1r3walled** [comment]
Hey,
I don't know what I made different, but now it worked.
I upgraded my Ubuntu installation to 16.04, but even following all steps, it did not work. I just tried to check all issues from the project repository and apply it.
The information appearing in the frontend has began after the command `sudo chown www-data:www-data /var/www/html -R` but honestly, I doubt that this was the issue (maybe I'm wrong). Anyway, that's a guess.
Something that I changed in this new installation that it is not specified in the instructions (and I'm not sure if it makes difference), but I also changed: 
backend.py (I replaced `0.0.0.0` by my VPS public IP address)
config.dist.yaml (I replaced `localhost` in the backend line by my VPS public IP address)

Inside `/var/www/html` I changed:
apiurl.js  (I replaced `localhost` by my VPS public IP)

Thank you for your support and congrats on your project. I'll keep watching it.
